name: Check Compilation

on:
  push:
    branches:
      - master

jobs:
  compilation:
    name: compilation
    - runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:devel
    steps:
      - uses: actions/checkout@v2
      name: run compilation
      run: |
        make
