name: Check Compilation

on:
  push:
    branches:
      - master

jobs:
  compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:devel
    steps:
      #Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      #Run
      - name: Build
        run: make

      - name: Chekout if binary exist
        run: ls my_hello
